/**
 * Access to the bundled OBS catalogue.
 *
 * The catalogue is ~230 KB of JSON, read via dynamic `import()` here so that,
 * once something calls into this module, it lands in its own chunk rather than
 * the entry bundle: a translator who opens their own recordings should not pay
 * for story metadata they are not using.
 *
 * As of #161, that "once something calls into this module" has not happened
 * yet — `getStory` and `listStories` are both `@pivotpending` with no caller in
 * `src/` (only tests import this file), so today the module is not reachable
 * from the app's entry point at all, produces no chunk, and the service worker
 * precache manifest has no `obs-catalog` entry to speak of. This corrects an
 * earlier claim here that the chunk was precached; verified against a
 * production `npm run build`'s `dist/` output, not assumed. Once B7's Template
 * Library (#33) wires up a caller, the dynamic import will start producing a
 * real chunk and the precache claim becomes worth re-checking.
 */

import type { ObsCatalog, ObsStory } from "@/types/obs";

let cached: ObsCatalog | null = null;

async function loadCatalog(): Promise<ObsCatalog> {
  cached ??= (await import("@/data/obs-catalog.json")).default as ObsCatalog;
  return cached;
}

/**
 * @pivotpending No caller yet. The app no longer boots from OBS (G2: the empty
 * Books screen). B7's Template Library (#33) reads a chosen story to seed a
 * book's segments, which is this seam's next reader. Tagged rather than left to
 * the test-only knip blind spot the OBS tests would otherwise hide it behind.
 */
export async function getStory(n: number): Promise<ObsStory | undefined> {
  const catalog = await loadCatalog();
  return catalog.stories.find((s) => s.story === n);
}

/**
 * @pivotpending No caller yet. Listing the available stories is the core read
 * of B7's Template Library (#33), where this module becomes a template
 * provider rather than the hard-wired OBS path it is today.
 */
export async function listStories(): Promise<
  readonly { story: number; title: string; frameCount: number }[]
> {
  const catalog = await loadCatalog();
  return catalog.stories.map((s) => ({
    story: s.story,
    title: s.title,
    frameCount: s.frames.length,
  }));
}

/**
 * The scope string identifying one OBS frame, in Scripture Burrito grammar.
 *
 * OBS is addressed as book "OBS" with story-as-chapter and frame-as-verse, so
 * story 1 frame 7 is `"1:7"`. This keeps OBS sections in the same addressing
 * scheme as scripture sections (`src/lib/scripture/scope.ts`) rather than
 * inventing a second one.
 *
 * Note the standard does not define an audio flavour for stories — see
 * docs/research/prior-art.md §4. This addressing is internally consistent and
 * burrito-shaped, but exporting OBS audio as a valid burrito remains unsolved.

 *
 * @pivotpending No caller yet, same as `getStory`/`listStories` above: B7's
 * Template Library (#33) is what writes `SegmentRef.scope` for an OBS-seeded
 * segment (`src/types/domain.ts:48`), and this is the function that builds it.
 */
export function obsFrameScope(story: number, frame: number): string {
  return `${story}:${frame}`;
}

/**
 * Path to a frame's bundled thumbnail.
 *
 * Thumbnails ship with the app (598 frames, 2.5 MB total) rather than being
 * downloaded: the CDN publishes 360px, the list renders at 48–56px, and
 * centre-cropped to 128px the whole set is small enough to bundle. That makes
 * the section list work offline on first run and removes per-story artwork
 * downloading from the primary path entirely.
 *
 * Generated by `scripts/build-obs-thumbs.mjs`.

 *
 * @pivotpending No caller yet. Per-segment artwork (D6) is on B7's Template
 * Library (#33) list too — "a template may also supply per-segment artwork" —
 * so this is the same seam as `getStory`/`listStories`/`obsFrameScope` above,
 * not a separate one.
 */
export function thumbUrl(story: number, frame: number): string {
  const s = String(story).padStart(2, "0");
  const f = String(frame).padStart(2, "0");
  return `/obs/thumbs/obs-${s}-${f}.jpg`;
}

/**
 * @pivotpending No caller yet. The USFM book code B7's OBS template writer
 * (#33) stamps onto `SegmentRef.book` for an OBS-seeded segment — kept here
 * rather than inlined at each call site so the two OBS-only literals ("OBS"
 * and this module's scope grammar) live in one place.
 */
export const OBS_BOOK_CODE = "OBS";
