/**
 * Access to the bundled OBS catalogue.
 *
 * The catalogue is ~230 KB of JSON. It is loaded via dynamic `import()` so it
 * does not sit in the entry chunk: a translator who opens their own recordings
 * should not pay for story metadata they are not using. That chunk is
 * precached only once a production module imports this file — today none
 * does, so Vite tree-shakes the dynamic `import()` out of the build and the
 * chunk is precached nowhere (ADR 0006, 2026-09-04 amendment).
 */

import type { ObsCatalog, ObsStory } from "@/types/obs";

let cached: ObsCatalog | null = null;

async function loadCatalog(): Promise<ObsCatalog> {
  cached ??= (await import("@/data/obs-catalog.json")).default as ObsCatalog;
  return cached;
}

/**
 * @pivotpending No caller yet. The app no longer boots from OBS (G2: the empty
 * Books screen). B7's Template Library (#33) reads a chosen story to seed a
 * book's segments, which is this seam's next reader. Tagged rather than left to
 * the test-only knip blind spot the OBS tests would otherwise hide it behind.
 */
export async function getStory(n: number): Promise<ObsStory | undefined> {
  const catalog = await loadCatalog();
  return catalog.stories.find((s) => s.story === n);
}

/**
 * @pivotpending No caller yet. Listing the available stories is the core read
 * of B7's Template Library (#33), where this module becomes a template
 * provider rather than the hard-wired OBS path it is today.
 */
export async function listStories(): Promise<
  readonly { story: number; title: string; frameCount: number }[]
> {
  const catalog = await loadCatalog();
  return catalog.stories.map((s) => ({
    story: s.story,
    title: s.title,
    frameCount: s.frames.length,
  }));
}

/**
 * The scope string identifying one OBS frame, in Scripture Burrito grammar.
 *
 * OBS is addressed as book "OBS" with story-as-chapter and frame-as-verse, so
 * story 1 frame 7 is `"1:7"`. This keeps OBS sections in the same addressing
 * scheme as scripture sections (the grammar in `tests/scope.ts`, test-only
 * since #818/#159) rather than inventing a second one.
 *
 * Note the standard does not define an audio flavour for stories — see
 * docs/research/prior-art.md §4. This addressing is internally consistent and
 * burrito-shaped, but exporting OBS audio as a valid burrito remains unsolved.
 *
 * @pivotpending No caller yet. #253 (Template Library, storage half) names
 * this function directly as the `SegmentRef` writer for an OBS-derived
 * segment's `reference`.
 */
export function obsFrameScope(story: number, frame: number): string {
  return `${story}:${frame}`;
}

/**
 * Path to a frame's bundled thumbnail.
 *
 * Thumbnails ship with the app (598 frames, 2.5 MB total) rather than being
 * downloaded: the CDN publishes 360px, the list renders at 48–56px, and
 * centre-cropped to 128px the whole set is small enough to bundle. That removes
 * per-story artwork downloading from the primary path entirely.
 *
 * They ship in the build but are currently **excluded from the service-worker
 * precache** (#177): this function has no caller yet, so no screen draws the
 * thumbnails and precaching them only delayed offline-readiness. When a screen
 * reads this (the Template Library, #33), `jpg` is restored to
 * `workbox.globPatterns` in `vite.config.ts` so the set is precached for
 * offline first-run again — see ADR 0006 (2026-09-04 amendment) and
 * `tests/precache-manifest.test.ts`.
 *
 * Generated by `scripts/build-obs-thumbs.mjs`.
 *
 * @pivotpending No caller yet. #246 (Template Library, UI half) names this
 * function directly as the thumbnail a story's picker row reads, and step 4
 * there is what restores `jpg` to `vite.config.ts`'s `globPatterns` once a
 * screen calls it.
 */
export function thumbUrl(story: number, frame: number): string {
  const s = String(story).padStart(2, "0");
  const f = String(frame).padStart(2, "0");
  return `/obs/thumbs/obs-${s}-${f}.jpg`;
}

/**
 * @pivotpending No caller yet. #253 pairs this with {@link obsFrameScope} to
 * address an OBS-derived `SegmentRef` ("OBS" the book, `obsFrameScope`'s
 * result the scope).
 */
export const OBS_BOOK_CODE = "OBS";
